Q1: Write a funciton that intentionally throws and error and use a try-catch block to handle the error and log an appropriate message to the console.

Q2: Create a funciton that divides two numbers and throw an error if the denominator is zero. Use a try-catch block to handle this error

Q3: Write a script that includes a try-catch block and a finally bloc. Log messages in the try, catch, and finally blocks to observe the execution flow

Q4: Create a custom error class that extends the built-in Error class. Throw an instance of this custom error in a funciton and handle it using a try catch block

Q5: Write a funciton that validates user input (e,g., checking if a string is not empty) and thros a custom error if the validation fails. Hanlde the custom error using a try-catch block

Q6: Create a promise that randomly resolves or rejects. Use .catch() to handle the rejection and log an appropriate message to the console

Q7: Use try-catch within an async funciton to handle error from a promise that randoley resolves or rejects, and log the error message

Q8: Use the fetch API to request data from an invalid URL and handle the error using .catch() Log an appropriate error message to the console"

Q9: Use the fetch API to request data from an invalid URL within an async funciton and handle the error using try-catch log and appropriate error message
